### ISSUE TITLE
code-review

### ISSUE THREAD

**Issue by pavelmickevic** [Pauliukas7/Adform#1]
Hey, I will leave some comments regarding the code here. I hope you don't mind

**Comment by pavelmickevic** [comment]
https://github.com/Pauliukas7/Adform/blob/4f0523e91d3ce9ebafc77f44ba2d8c15953403a0/src/components/AddCampaignBox.js#L32-L33

be sure, you understand, why you used `toLocaleString` ?

**Comment by pavelmickevic** [comment]
https://github.com/Pauliukas7/Adform/blob/5d09906bc57f7bd6f505a421c1c4045a96efc723/src/components/InputFields.js#L27

sadly, you didn't think about validating `start` and `end` fields. Currenly, I can add `startDate` greater than `endDate`. You should always challenge yourself for such, when working with date ranges from...to 

--- 

you didn't use any date-related library, I can see all around `new Date` and `getTime` and `>=, <` combinations.

Please read about `moment` and its methods like `isBefore` or `isSameOrAfter`. This can be handy in your case. 

this below looks ugly :) think of how you can refactor it. 

```
const todaysDateInMillis = new Date().getTime();
...
{todaysDateInMillis < new Date(props.endDate).getTime() &&...
```

**Comment by pavelmickevic** [comment]
```
state.inputsslice
```

property name look ugly. Read about [Case Styles: Camel, Pascal, Snake, and Kebab Case](https://betterprogramming.pub/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841)

**Comment by pavelmickevic** [comment]
https://github.com/Pauliukas7/Adform/blob/4f0523e91d3ce9ebafc77f44ba2d8c15953403a0/src/components/CampaignTable.js#L14-L20

this is pretty good: 
1. loading true
2. make request
3. handle the **success** response
4. loading false (having it in `finally` is very elegant) 

Happy-flow is covered! 🥇 

--- 
You didn't do anything to handle bad request. Sometimes API's fail: either we show a red toaster or at least something.

**Comment by pavelmickevic** [comment]
https://github.com/Pauliukas7/Adform/blob/4f0523e91d3ce9ebafc77f44ba2d8c15953403a0/src/components/CampaignTable.js#L33

pardon my language, but..... 

wtf is `* 10`? :D what pattern is that? 

```
moment(new Date().getTime()).format('YYYY-MM-DD')
'2022-01-20'

moment(new Date().getTime() * 10).format('YYYY-MM-DD')
'2490-07-17'
```

you should never multiply dates :D

**Comment by Pauliukas7** [comment]
Hello, thank you for your comments. I just wanted to know, should I get on
with refactoring the code? or wait for your further emails?

2022-01-20, kt, 12:39 Pavel Mickevic ***@***.***> rašė:

**Comment by pavelmickevic** [comment]
no no! 
leave it, I think. But read the links I shared, when you have time. 

---


> wait for your further emails

Could you wait a little bit more?
